server:
  port: 8080

spring:
  application:
    name: board

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: hanjea!1298

  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: update